name: Build Nginx
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            git
            make
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-make
      - shell: msys2 {0}
        run: |
          echo "$env:MSYS2_LOCATION"
          ls "D:\a\_temp\msys64"
      - name: Download and extract Nginx source
        shell: msys2 {0}
        run: |
          ls -al
          pwd
          wget https://nginx.org/download/nginx-1.25.3.tar.gz
          tar -xzf nginx-1.25.3.tar.gz
          cd nginx-1.25.3
          mkdir lib
          cd lib 
          wget https://github.com/openssl/openssl/releases/download/openssl-3.5.0/openssl-3.5.0.tar.gz
          tar -xzvf openssl-3.5.0.tar.gz
          wget https://zlib.net/zlib-1.3.1.tar.gz
          tar -xzvf zlib-1.3.1.tar.gz
          wget -O pcre-8.45.tar.gz https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download
          tar -xzvf pcre-8.45.tar.gz
          ls -al
          pwd
      - name: Configure and build Nginx
        shell: msys2 {0}
        run: |
          ls -al
          pwd
          cd nginx-1.25.3
          pwd
          ./configure \
            --prefix=/mingw64/nginx \
            --with-http_ssl_module \
            --with-pcre=lib/pcre-8.45 \
            --with-zlib=lib/zlib-1.3.1 \
            --with-openssl=lib/openssl-3.5.0
          make -j32
      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: nginx-windows-bin
          path: D:\a\_temp\msys64\mingw64\nginx