name: Build Nginx
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-make
      - shell: msys2 {0}
        run: |
          echo "$env:MSYS2_LOCATION"
          ls "D:\a\_temp\msys64"
      - name: Download and extract Nginx source
        shell: cmd
        run: |
          msys2 -c "
            wget https://nginx.org/download/nginx-1.25.3.tar.gz
            tar -xzf nginx-1.25.3.tar.gz
            cd nginx-1.25.3
          "
      - name: Configure and build Nginx
        shell: cmd
        run: |
          msys2 -c "
            cd nginx-1.25.3
            ./configure \
              --prefix=/mingw64/nginx \
              --with-http_ssl_module \
              --with-pcre=/mingw64/include \
              --with-zlib=/mingw64/include \
              --with-openssl=/mingw64/include \
              --with-cc-opt='-static'
            make -j4
            make install
          "