name: Build Nginx
on: [push]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          install: >-
            git
            make
      - env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: |
          echo "$env:MSYS2_LOCATION"
          ls "D:\a\_temp\msys64"
      - name: Download and extract Nginx source
        run: |
          ls -al
          pwd
          wget https://nginx.org/download/nginx-1.26.3.tar.gz
          tar -xzf nginx-1.26.3.tar.gz
          mv nginx-1.26.3 nginx
          cd nginx
          mkdir lib
          cd lib 
          wget https://github.com/openssl/openssl/releases/download/openssl-3.5.0/openssl-3.5.0.tar.gz
          tar -xzvf openssl-3.5.0.tar.gz
          wget https://zlib.net/zlib-1.3.1.tar.gz
          tar -xzvf zlib-1.3.1.tar.gz
          wget -O pcre-8.45.tar.gz https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.gz/download
          tar -xzvf pcre-8.45.tar.gz
          ls -al
          pwd
      - name: Configure and build Nginx
        shell: msys2 {0}
        run: |
          ls -al
          pwd
          cd nginx
          pwd
          ./configure \
            --prefix= \
            --conf-path=conf/nginx.conf \
            --pid-path=logs/nginx.pid \
            --http-log-path=logs/access.log \
            --error-log-path=logs/error.log \
            --sbin-path=nginx.exe \
            --http-client-body-temp-path=temp/client_body_temp \
            --http-proxy-temp-path=temp/proxy_temp \
            --http-fastcgi-temp-path=temp/fastcgi_temp \
            --http-scgi-temp-path=temp/scgi_temp \
            --http-uwsgi-temp-path=temp/uwsgi_temp \
            --with-cc-opt=-DFD_SETSIZE=1024 \
            --with-pcre=lib/pcre-8.45 \
            --with-zlib=lib/zlib-1.3.1 \
            --with-openssl=lib/openssl-3.5.0 \
            --with-openssl-opt='no-asm no-tests -D_WIN32_WINNT=0x0601' \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-http_realip_module \
            --with-http_addition_module \
            --with-http_sub_module \
            --with-http_stub_status_module \
            --with-http_flv_module \
            --with-http_mp4_module \
            --with-http_gunzip_module \
            --with-http_gzip_static_module \
            --with-http_auth_request_module \
            --with-http_random_index_module \
            --with-http_secure_link_module \
            --with-http_slice_module \
            --with-mail \
            --with-mail_ssl_module \
            --with-stream \
            --with-stream_ssl_module \
            --with-stream_ssl_preread_module \
            --with-http_dav_module
          make -j4
          cp objs/nginx.exe ../
      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: nginx-v1.26.3
          path: nginx.exe