name: Build Nginx
on: [push]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-pcre
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-make
        env:
          MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
        run: echo "$env:MSYS2_LOCATION"