name: Build Nginx
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msys2_root: C:\msys64
          components:  # 安装必要的组件
            - mingw64/mingw-w64-x86_64-toolchain
            - mingw64/mingw-w64-x86_64-pkg-config
            - mingw64/mingw-w64-x86_64-zlib
            - mingw64/mingw-w64-x86_64-pcre
            - mingw64/mingw-w64-x86_64-openssl
            - mingw64/mingw-w64-x86_64-make
      - name: Install additional dependencies
        shell: cmd
        run: |
          C:\msys64\msys2_shell.cmd -mingw64 -c "
            pacman -S --noconfirm --needed \
              mingw-w64-x86_64-gcc \
              mingw-w64-x86_64-gcc-libs \
              mingw-w64-x86_64-gcc-objc \
              mingw-w64-x86_64-gcc-fortran
          "
